name "apt-s3"
maintainer "ADADA, LLC"
maintainer_email "david@adadabase.com"
license "MIT"
description "Builds and installs apt-s3, enabling package management via S3."
version "0.1.0"
depends "apt"
depends "build-essential"
